### PR TITLE
Added two new functions to help with Objects.

### PR DESCRIPTION
**Pull request by fergqwertyui**
# Requirements

- [x] The base branch is pointing to the correct branch. 

## Codebase

- [x] This code has been tested with the [latest release](https://github.com/EasyScriptJS/EasyScript/releases/latest) of Easy Script.
- [x] This code works with the [latest release](https://github.com/EasyScriptJS/EasyScript/releases/latest) of Easy Script.
- [x] This code has been run through [Prettier](https://prettier.io).

### Modules

- [x] I have provided documentation of how this code works. 

# Description

Added two functions:
1) 'isEmpty' easily lets you check whether a JS object or array is empty or not.
2) 'matches' provides a deep check to see whether two arrays or objects match entirely.

# Reason

These functions are useful and make everyday JS quicker.

### CODE REVIEW

**Comment by avalynndev** [comment]
reviewing pr

**Review by avalynndev — DISMISSED** [review]
Pls revert changes in package-lock.json

**Review by avalynndev — COMMENTED** [review]
Does this work ? Because I don't like something that ain't working.

**Review by WilliamDavidHarrison — CHANGES_REQUESTED** [review]
Hey there, please revert the changes to the `package-lock.json` file, alphabetise the modules in the `index.ts` file, and provide documentation on how the modules work.

**Comment by fergqwertyui** [comment]
Docs pull request made here:
[https://github.com/EasyScriptJS/ts/pull/1](url)

**Review by WilliamDavidHarrison — APPROVED** [review]
LGTM @avalynndev

**Review by avalynndev — APPROVED** [review]

**Pull request merged**
